"""Database access helpers for the 3D generation pipeline.

Covers ``MediaSubmission`` (the async generation job record) and ``MapObject``
(the placed mesh produced on success). The service layer owns transactions and
authorization; these helpers only read and write rows.
"""

from uuid import UUID

from app.models.location_pin_model import LocationPin
from app.models.map_object_model import MapObject
from app.models.media_submission_model import (
    SUBMISSION_STATUS_FAILED,
    SUBMISSION_STATUS_READY,
    MediaSubmission,
)
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload


async def create_submission(
    db: AsyncSession,
    *,
    submission_id: UUID,
    group_id: UUID,
    pin_id: UUID,
    user_id: UUID,
    source_image_key: str,
) -> MediaSubmission:
    """Persist a new submission in the ``processing`` state.

    The ``submission_id`` is generated by the service so the storage key can be
    built before the row is inserted.
    """
    submission = MediaSubmission(
        id=submission_id,
        group_id=group_id,
        pin_id=pin_id,
        user_id=user_id,
        source_image_key=source_image_key,
    )
    db.add(submission)
    await db.flush()
    await db.refresh(submission)
    return submission


async def get_submission(
    db: AsyncSession,
    submission_id: UUID,
) -> MediaSubmission | None:
    """Return a submission by id, or ``None`` if it does not exist."""
    result = await db.execute(
        select(MediaSubmission).where(MediaSubmission.id == submission_id)
    )
    return result.scalar_one_or_none()


async def get_pin(db: AsyncSession, pin_id: UUID) -> LocationPin | None:
    """Return a location pin by id, or ``None`` if it does not exist."""
    result = await db.execute(select(LocationPin).where(LocationPin.id == pin_id))
    return result.scalar_one_or_none()


async def mark_submission_ready(
    db: AsyncSession,
    submission: MediaSubmission,
    *,
    mesh_storage_key: str,
    mesh_public_url: str,
) -> MapObject:
    """Mark a submission ``ready`` and create its map object.

    Copies the pin's coordinates onto the ``MapObject`` so the map-state
    endpoint can place the mesh without an extra join. Commits the transaction.
    """
    submission.status = SUBMISSION_STATUS_READY
    submission.mesh_storage_key = mesh_storage_key
    submission.mesh_public_url = mesh_public_url
    submission.error_message = None

    pin = await get_pin(db, submission.pin_id)
    if pin is None:
        raise ValueError(f"Pin {submission.pin_id} no longer exists.")

    map_object = MapObject(
        group_id=submission.group_id,
        pin_id=submission.pin_id,
        submission_id=submission.id,
        lat=pin.lat,
        lng=pin.lng,
        mesh_public_url=mesh_public_url,
    )
    db.add(map_object)

    await db.commit()
    await db.refresh(map_object)
    return map_object


async def mark_submission_failed(
    db: AsyncSession,
    submission: MediaSubmission,
    *,
    error_message: str,
) -> MediaSubmission:
    """Mark a submission ``failed`` with an error message. Commits."""
    submission.status = SUBMISSION_STATUS_FAILED
    submission.error_message = error_message[:1000]
    await db.commit()
    await db.refresh(submission)
    return submission


async def list_submissions_for_pin(
    db: AsyncSession,
    group_id: UUID,
    pin_id: UUID,
) -> list[MediaSubmission]:
    """Return all submissions for a pin within a group, newest first."""
    result = await db.execute(
        select(MediaSubmission)
        .where(
            MediaSubmission.group_id == group_id,
            MediaSubmission.pin_id == pin_id,
        )
        .order_by(MediaSubmission.created_at.desc())
    )
    return list(result.scalars().all())


async def list_submissions_for_group(
    db: AsyncSession,
    group_id: UUID,
) -> list[MediaSubmission]:
    """Return all submissions for a group, newest first."""
    result = await db.execute(
        select(MediaSubmission)
        .where(MediaSubmission.group_id == group_id)
        .order_by(MediaSubmission.created_at.desc())
    )
    return list(result.scalars().all())


async def list_map_objects_for_group(
    db: AsyncSession,
    group_id: UUID,
    *,
    bbox: tuple[float, float, float, float] | None = None,
) -> list[MapObject]:
    """Return generated map objects for a group, oldest first.

    Eager-loads the anchoring pin so callers can read ``osm_building_id``
    without a lazy load. When ``bbox`` (min_lng, min_lat, max_lng, max_lat)
    is given, only objects whose coordinates fall inside it are returned.
    """
    query = (
        select(MapObject)
        .options(selectinload(MapObject.pin))
        .where(MapObject.group_id == group_id)
        .order_by(MapObject.created_at.asc())
    )
    if bbox is not None:
        min_lng, min_lat, max_lng, max_lat = bbox
        query = query.where(
            MapObject.lng >= min_lng,
            MapObject.lng <= max_lng,
            MapObject.lat >= min_lat,
            MapObject.lat <= max_lat,
        )
    result = await db.execute(query)
    return list(result.scalars().all())


async def get_map_object_for_group(
    db: AsyncSession,
    group_id: UUID,
    object_id: UUID,
) -> MapObject | None:
    """Return a single map object scoped to a group, with its pin loaded."""
    result = await db.execute(
        select(MapObject)
        .options(selectinload(MapObject.pin))
        .where(MapObject.id == object_id, MapObject.group_id == group_id)
    )
    return result.scalar_one_or_none()


async def update_map_object_transform(
    db: AsyncSession,
    map_object: MapObject,
    *,
    heading: float,
    scale: float,
) -> MapObject:
    """Persist a new ``heading`` (yaw in degrees) and ``scale`` multiplier on a
    map object. Commits."""
    map_object.heading = heading
    map_object.scale = scale
    await db.commit()
    await db.refresh(map_object)
    return map_object
